
﻿





#pragma warning disable 1591
#pragma warning disable 0108
#pragma warning disable 0114

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Linq;
using System.Text;
using Sitecore.Globalization;
using Sitecore.Data;

﻿








namespace Sitecore.Feature.Blog.Models
{

	
	/// <summary>
	/// BlogRelatedListing
	/// <para></para>
	/// <para>Path: /sitecore/templates/Feature/Blog/_Blog Related Listing</para>	
	/// <para>ID: 0607865c-c480-4837-a6f0-02e23c74c815</para>	
	/// </summary>
	public partial class BlogRelatedListing 
	{
			public const string TemplateIdString = "0607865c-c480-4837-a6f0-02e23c74c815";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "_Blog Related Listing";

			   
			public const string RelatedBlogPostsFieldIdRaw = "324f8f13-0706-4538-89b6-71687d5f31d2";
			public static readonly ID RelatedBlogPostsFieldId = new ID("324f8f13-0706-4538-89b6-71687d5f31d2");
			public const string RelatedBlogPostsFieldName = "Related Blog Posts";
			
			}
}
﻿








namespace Sitecore.Feature.Blog.Models
{

	
	/// <summary>
	/// TitleParameters
	/// <para></para>
	/// <para>Path: /sitecore/templates/Feature/Blog/Title Parameters</para>	
	/// <para>ID: 1d15c746-52d2-484e-a528-439583f898aa</para>	
	/// </summary>
	public partial class TitleParameters 
	{
			public const string TemplateIdString = "1d15c746-52d2-484e-a528-439583f898aa";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Title Parameters";

			   
			public const string RenderingTitleFieldIdRaw = "bed1685e-527f-4c77-a359-fd18b37bf820";
			public static readonly ID RenderingTitleFieldId = new ID("bed1685e-527f-4c77-a359-fd18b37bf820");
			public const string RenderingTitleFieldName = "Rendering Title";
			
			}
}
﻿








namespace Sitecore.Feature.Blog.Models
{

	
	/// <summary>
	/// BlogListingParameters
	/// <para></para>
	/// <para>Path: /sitecore/templates/Feature/Blog/Blog Listing Parameters</para>	
	/// <para>ID: 26482946-622b-45cc-991b-23aa148d83dd</para>	
	/// </summary>
	public partial class BlogListingParameters 
	{
			public const string TemplateIdString = "26482946-622b-45cc-991b-23aa148d83dd";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Blog Listing Parameters";

			   
			public const string PostsPerPageFieldIdRaw = "0735feb1-c8c7-48b0-beb6-9f7f5b5c06f5";
			public static readonly ID PostsPerPageFieldId = new ID("0735feb1-c8c7-48b0-beb6-9f7f5b5c06f5");
			public const string PostsPerPageFieldName = "Posts Per Page";
			
			}
}
﻿








namespace Sitecore.Feature.Blog.Models
{

	
	/// <summary>
	/// BlogSlug
	/// <para></para>
	/// <para>Path: /sitecore/templates/Feature/Blog/_Blog Slug</para>	
	/// <para>ID: 343df744-b726-480b-954f-d4ab5e08d7d4</para>	
	/// </summary>
	public partial class BlogSlug 
	{
			public const string TemplateIdString = "343df744-b726-480b-954f-d4ab5e08d7d4";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "_Blog Slug";

			   
			public const string SlugFieldIdRaw = "8e301bcf-11ae-40bd-9465-4ca58351c8f6";
			public static readonly ID SlugFieldId = new ID("8e301bcf-11ae-40bd-9465-4ca58351c8f6");
			public const string SlugFieldName = "Slug";
			
			}
}
﻿








namespace Sitecore.Feature.Blog.Models
{

	
	/// <summary>
	/// BlogAuthor
	/// <para></para>
	/// <para>Path: /sitecore/templates/Feature/Blog/Blog Author</para>	
	/// <para>ID: 702b64d5-58da-475f-843f-5bdf09a40e36</para>	
	/// </summary>
	public partial class BlogAuthor 
	{
			public const string TemplateIdString = "702b64d5-58da-475f-843f-5bdf09a40e36";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Blog Author";

			   
			public const string BiographyFieldIdRaw = "a2fcf996-31b1-4593-949f-8cd09e14d752";
			public static readonly ID BiographyFieldId = new ID("a2fcf996-31b1-4593-949f-8cd09e14d752");
			public const string BiographyFieldName = "Biography";
			
			   
			public const string FullNameFieldIdRaw = "d23d9a16-ae41-4e2f-b191-08be5d1122a3";
			public static readonly ID FullNameFieldId = new ID("d23d9a16-ae41-4e2f-b191-08be5d1122a3");
			public const string FullNameFieldName = "Full Name";
			
			   
			public const string ProfileImageFieldIdRaw = "9296604a-dd41-4ddd-8e7b-ab0b8930a07f";
			public static readonly ID ProfileImageFieldId = new ID("9296604a-dd41-4ddd-8e7b-ab0b8930a07f");
			public const string ProfileImageFieldName = "Profile Image";
			
			   
			public const string TitleFieldIdRaw = "4c045da9-9969-49f8-9f7f-6c7a7b607f18";
			public static readonly ID TitleFieldId = new ID("4c045da9-9969-49f8-9f7f-6c7a7b607f18");
			public const string TitleFieldName = "Title";
			
			   
			public const string SlugFieldIdRaw = "8e301bcf-11ae-40bd-9465-4ca58351c8f6";
			public static readonly ID SlugFieldId = new ID("8e301bcf-11ae-40bd-9465-4ca58351c8f6");
			public const string SlugFieldName = "Slug";
			
			   
			public const string PageDescriptionFieldIdRaw = "59c2a8de-aabe-4a6e-9ad0-4ccde7e93d8f";
			public static readonly ID PageDescriptionFieldId = new ID("59c2a8de-aabe-4a6e-9ad0-4ccde7e93d8f");
			public const string PageDescriptionFieldName = "Page Description";
			
			   
			public const string PageTitleFieldIdRaw = "754e9622-8e08-4e3f-9b83-eb8d99bba99c";
			public static readonly ID PageTitleFieldId = new ID("754e9622-8e08-4e3f-9b83-eb8d99bba99c");
			public const string PageTitleFieldName = "Page Title";
			
			}
}
﻿








namespace Sitecore.Feature.Blog.Models
{

	
	/// <summary>
	/// RecentListingParameters
	/// <para></para>
	/// <para>Path: /sitecore/templates/Feature/Blog/Recent Listing Parameters</para>	
	/// <para>ID: 8aa54159-bc1f-40fa-b050-53fea1dda654</para>	
	/// </summary>
	public partial class RecentListingParameters 
	{
			public const string TemplateIdString = "8aa54159-bc1f-40fa-b050-53fea1dda654";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Recent Listing Parameters";

			   
			public const string RenderingTitleFieldIdRaw = "bed1685e-527f-4c77-a359-fd18b37bf820";
			public static readonly ID RenderingTitleFieldId = new ID("bed1685e-527f-4c77-a359-fd18b37bf820");
			public const string RenderingTitleFieldName = "Rendering Title";
			
			   
			public const string PostsPerPageFieldIdRaw = "0735feb1-c8c7-48b0-beb6-9f7f5b5c06f5";
			public static readonly ID PostsPerPageFieldId = new ID("0735feb1-c8c7-48b0-beb6-9f7f5b5c06f5");
			public const string PostsPerPageFieldName = "Posts Per Page";
			
			}
}
﻿








namespace Sitecore.Feature.Blog.Models
{

	
	/// <summary>
	/// BlogTag
	/// <para></para>
	/// <para>Path: /sitecore/templates/Feature/Blog/Blog Tag</para>	
	/// <para>ID: b05c5f99-615b-46e4-a0f0-fb43e62c404f</para>	
	/// </summary>
	public partial class BlogTag 
	{
			public const string TemplateIdString = "b05c5f99-615b-46e4-a0f0-fb43e62c404f";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Blog Tag";

			   
			public const string TagNameFieldIdRaw = "94009472-3730-4f62-a8c7-3750baf1d57b";
			public static readonly ID TagNameFieldId = new ID("94009472-3730-4f62-a8c7-3750baf1d57b");
			public const string TagNameFieldName = "Tag Name";
			
			   
			public const string SlugFieldIdRaw = "8e301bcf-11ae-40bd-9465-4ca58351c8f6";
			public static readonly ID SlugFieldId = new ID("8e301bcf-11ae-40bd-9465-4ca58351c8f6");
			public const string SlugFieldName = "Slug";
			
			   
			public const string PageDescriptionFieldIdRaw = "59c2a8de-aabe-4a6e-9ad0-4ccde7e93d8f";
			public static readonly ID PageDescriptionFieldId = new ID("59c2a8de-aabe-4a6e-9ad0-4ccde7e93d8f");
			public const string PageDescriptionFieldName = "Page Description";
			
			   
			public const string PageTitleFieldIdRaw = "754e9622-8e08-4e3f-9b83-eb8d99bba99c";
			public static readonly ID PageTitleFieldId = new ID("754e9622-8e08-4e3f-9b83-eb8d99bba99c");
			public const string PageTitleFieldName = "Page Title";
			
			}
}
﻿








namespace Sitecore.Feature.Blog.Models
{

	
	/// <summary>
	/// PageHeader
	/// <para></para>
	/// <para>Path: /sitecore/templates/Feature/Blog/_Page Header</para>	
	/// <para>ID: b5f7cb20-18ae-4d18-95fe-502c69e0320f</para>	
	/// </summary>
	public partial class PageHeader 
	{
			public const string TemplateIdString = "b5f7cb20-18ae-4d18-95fe-502c69e0320f";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "_Page Header";

			   
			public const string PageDescriptionFieldIdRaw = "59c2a8de-aabe-4a6e-9ad0-4ccde7e93d8f";
			public static readonly ID PageDescriptionFieldId = new ID("59c2a8de-aabe-4a6e-9ad0-4ccde7e93d8f");
			public const string PageDescriptionFieldName = "Page Description";
			
			   
			public const string PageTitleFieldIdRaw = "754e9622-8e08-4e3f-9b83-eb8d99bba99c";
			public static readonly ID PageTitleFieldId = new ID("754e9622-8e08-4e3f-9b83-eb8d99bba99c");
			public const string PageTitleFieldName = "Page Title";
			
			}
}
﻿








namespace Sitecore.Feature.Blog.Models
{

	
	/// <summary>
	/// BlogCategory
	/// <para></para>
	/// <para>Path: /sitecore/templates/Feature/Blog/Blog Category</para>	
	/// <para>ID: b8b0484c-f1a9-4a18-afa4-a7b942063d54</para>	
	/// </summary>
	public partial class BlogCategory 
	{
			public const string TemplateIdString = "b8b0484c-f1a9-4a18-afa4-a7b942063d54";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Blog Category";

			   
			public const string CategoryNameFieldIdRaw = "c77f7b33-3503-4f24-84d9-766735e2ef12";
			public static readonly ID CategoryNameFieldId = new ID("c77f7b33-3503-4f24-84d9-766735e2ef12");
			public const string CategoryNameFieldName = "Category Name";
			
			   
			public const string SlugFieldIdRaw = "8e301bcf-11ae-40bd-9465-4ca58351c8f6";
			public static readonly ID SlugFieldId = new ID("8e301bcf-11ae-40bd-9465-4ca58351c8f6");
			public const string SlugFieldName = "Slug";
			
			   
			public const string PageDescriptionFieldIdRaw = "59c2a8de-aabe-4a6e-9ad0-4ccde7e93d8f";
			public static readonly ID PageDescriptionFieldId = new ID("59c2a8de-aabe-4a6e-9ad0-4ccde7e93d8f");
			public const string PageDescriptionFieldName = "Page Description";
			
			   
			public const string PageTitleFieldIdRaw = "754e9622-8e08-4e3f-9b83-eb8d99bba99c";
			public static readonly ID PageTitleFieldId = new ID("754e9622-8e08-4e3f-9b83-eb8d99bba99c");
			public const string PageTitleFieldName = "Page Title";
			
			}
}
﻿








namespace Sitecore.Feature.Blog.Models
{

	
	/// <summary>
	/// BlogPost
	/// <para></para>
	/// <para>Path: /sitecore/templates/Feature/Blog/Blog Post</para>	
	/// <para>ID: bd48d35d-ae82-4269-8e9e-b21a5f17b363</para>	
	/// </summary>
	public partial class BlogPost 
	{
			public const string TemplateIdString = "bd48d35d-ae82-4269-8e9e-b21a5f17b363";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Blog Post";

			   
			public const string BodyFieldIdRaw = "1aa7b20f-f9cb-4d62-8ea1-10e688c8cd85";
			public static readonly ID BodyFieldId = new ID("1aa7b20f-f9cb-4d62-8ea1-10e688c8cd85");
			public const string BodyFieldName = "Body";
			
			   
			public const string PostTitleFieldIdRaw = "9e2f62d5-f204-4a4d-be1c-c6fb194e1226";
			public static readonly ID PostTitleFieldId = new ID("9e2f62d5-f204-4a4d-be1c-c6fb194e1226");
			public const string PostTitleFieldName = "Post Title";
			
			   
			public const string PublishDateFieldIdRaw = "24604281-35a6-4600-8890-081e79f1b0ab";
			public static readonly ID PublishDateFieldId = new ID("24604281-35a6-4600-8890-081e79f1b0ab");
			public const string PublishDateFieldName = "Publish Date";
			
			   
			public const string SummaryFieldIdRaw = "0eddfefb-fcc9-4b53-843b-b0acb10adc21";
			public static readonly ID SummaryFieldId = new ID("0eddfefb-fcc9-4b53-843b-b0acb10adc21");
			public const string SummaryFieldName = "Summary";
			
			   
			public const string ThumbnailFieldIdRaw = "544ac492-1308-4aa1-9672-31031a71a1f7";
			public static readonly ID ThumbnailFieldId = new ID("544ac492-1308-4aa1-9672-31031a71a1f7");
			public const string ThumbnailFieldName = "Thumbnail";
			
			   
			public const string AuthorsFieldIdRaw = "990d2a0c-1c4f-4db9-9cd2-bd110bcbb4f1";
			public static readonly ID AuthorsFieldId = new ID("990d2a0c-1c4f-4db9-9cd2-bd110bcbb4f1");
			public const string AuthorsFieldName = "Authors";
			
			   
			public const string CategoriesFieldIdRaw = "9eea7505-a172-4772-9164-61818f59e299";
			public static readonly ID CategoriesFieldId = new ID("9eea7505-a172-4772-9164-61818f59e299");
			public const string CategoriesFieldName = "Categories";
			
			   
			public const string TagsFieldIdRaw = "7a15403a-1086-4334-9610-bcee8db49cd9";
			public static readonly ID TagsFieldId = new ID("7a15403a-1086-4334-9610-bcee8db49cd9");
			public const string TagsFieldName = "Tags";
			
			   
			public const string SlugFieldIdRaw = "8e301bcf-11ae-40bd-9465-4ca58351c8f6";
			public static readonly ID SlugFieldId = new ID("8e301bcf-11ae-40bd-9465-4ca58351c8f6");
			public const string SlugFieldName = "Slug";
			
			}
}
﻿








namespace Sitecore.Feature.Blog.Models
{

	
	/// <summary>
	/// FilterParameter
	/// <para></para>
	/// <para>Path: /sitecore/templates/Feature/Blog/_Filter Parameter</para>	
	/// <para>ID: beb3562c-d9a7-4272-a1d4-22e151f0cd43</para>	
	/// </summary>
	public partial class FilterParameter 
	{
			public const string TemplateIdString = "beb3562c-d9a7-4272-a1d4-22e151f0cd43";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "_Filter Parameter";

			   
			public const string PostsPerPageFieldIdRaw = "0735feb1-c8c7-48b0-beb6-9f7f5b5c06f5";
			public static readonly ID PostsPerPageFieldId = new ID("0735feb1-c8c7-48b0-beb6-9f7f5b5c06f5");
			public const string PostsPerPageFieldName = "Posts Per Page";
			
			}
}
﻿








namespace Sitecore.Feature.Blog.Models
{

	
	/// <summary>
	/// Blog
	/// <para></para>
	/// <para>Path: /sitecore/templates/Feature/Blog/Blog</para>	
	/// <para>ID: e58b747b-d2d4-4db9-a535-0dec41bc4f2a</para>	
	/// </summary>
	public partial class Blog 
	{
			public const string TemplateIdString = "e58b747b-d2d4-4db9-a535-0dec41bc4f2a";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Blog";

			   
			public const string PageDescriptionFieldIdRaw = "59c2a8de-aabe-4a6e-9ad0-4ccde7e93d8f";
			public static readonly ID PageDescriptionFieldId = new ID("59c2a8de-aabe-4a6e-9ad0-4ccde7e93d8f");
			public const string PageDescriptionFieldName = "Page Description";
			
			   
			public const string PageTitleFieldIdRaw = "754e9622-8e08-4e3f-9b83-eb8d99bba99c";
			public static readonly ID PageTitleFieldId = new ID("754e9622-8e08-4e3f-9b83-eb8d99bba99c");
			public const string PageTitleFieldName = "Page Title";
			
			}
}
