
﻿





#pragma warning disable 1591
#pragma warning disable 0108
#pragma warning disable 0114

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Linq;
using System.Text;
using Sitecore.Globalization;
using Sitecore.Data;

﻿








namespace Sitecore.Feature.Blog.Sitecore.Feature.Blog.Feature.Blog
{

	
	/// <summary>
	/// BlogAuthors
	/// <para></para>
	/// <para>Path: /sitecore/templates/Feature/Blog/Blog Authors</para>	
	/// <para>ID: 524bc597-b41e-4673-8cc6-574fe788ba77</para>	
	/// </summary>
	public partial class BlogAuthors 
	{
			public const string TemplateIdString = "524bc597-b41e-4673-8cc6-574fe788ba77";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Blog Authors";

			}
}
﻿








namespace Sitecore.Feature.Blog.Sitecore.Feature.Blog.Feature.Blog
{

	
	/// <summary>
	/// BlogAuthor
	/// <para></para>
	/// <para>Path: /sitecore/templates/Feature/Blog/Blog Author</para>	
	/// <para>ID: 702b64d5-58da-475f-843f-5bdf09a40e36</para>	
	/// </summary>
	public partial class BlogAuthor 
	{
			public const string TemplateIdString = "702b64d5-58da-475f-843f-5bdf09a40e36";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Blog Author";

			   
			public const string BiographyFieldIdRaw = "a2fcf996-31b1-4593-949f-8cd09e14d752";
			public static readonly ID BiographyFieldId = new ID("a2fcf996-31b1-4593-949f-8cd09e14d752");
			public const string BiographyFieldName = "Biography";
			
			   
			public const string FullNameFieldIdRaw = "d23d9a16-ae41-4e2f-b191-08be5d1122a3";
			public static readonly ID FullNameFieldId = new ID("d23d9a16-ae41-4e2f-b191-08be5d1122a3");
			public const string FullNameFieldName = "Full Name";
			
			   
			public const string ProfileImageFieldIdRaw = "9296604a-dd41-4ddd-8e7b-ab0b8930a07f";
			public static readonly ID ProfileImageFieldId = new ID("9296604a-dd41-4ddd-8e7b-ab0b8930a07f");
			public const string ProfileImageFieldName = "Profile Image";
			
			   
			public const string TitleFieldIdRaw = "4c045da9-9969-49f8-9f7f-6c7a7b607f18";
			public static readonly ID TitleFieldId = new ID("4c045da9-9969-49f8-9f7f-6c7a7b607f18");
			public const string TitleFieldName = "Title";
			
			}
}
﻿








namespace Sitecore.Feature.Blog.Sitecore.Feature.Blog.Feature.Blog
{

	
	/// <summary>
	/// BlogTag
	/// <para></para>
	/// <para>Path: /sitecore/templates/Feature/Blog/Blog Tag</para>	
	/// <para>ID: b05c5f99-615b-46e4-a0f0-fb43e62c404f</para>	
	/// </summary>
	public partial class BlogTag 
	{
			public const string TemplateIdString = "b05c5f99-615b-46e4-a0f0-fb43e62c404f";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Blog Tag";

			   
			public const string BlogTagFieldIdRaw = "94009472-3730-4f62-a8c7-3750baf1d57b";
			public static readonly ID BlogTagFieldId = new ID("94009472-3730-4f62-a8c7-3750baf1d57b");
			public const string BlogTagFieldName = "Blog Tag";
			
			}
}
﻿








namespace Sitecore.Feature.Blog.Sitecore.Feature.Blog.Feature.Blog
{

	
	/// <summary>
	/// BlogCategory
	/// <para></para>
	/// <para>Path: /sitecore/templates/Feature/Blog/Blog Category</para>	
	/// <para>ID: b8b0484c-f1a9-4a18-afa4-a7b942063d54</para>	
	/// </summary>
	public partial class BlogCategory 
	{
			public const string TemplateIdString = "b8b0484c-f1a9-4a18-afa4-a7b942063d54";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Blog Category";

			   
			public const string CategoryNameFieldIdRaw = "c77f7b33-3503-4f24-84d9-766735e2ef12";
			public static readonly ID CategoryNameFieldId = new ID("c77f7b33-3503-4f24-84d9-766735e2ef12");
			public const string CategoryNameFieldName = "Category Name";
			
			}
}
﻿








namespace Sitecore.Feature.Blog.Sitecore.Feature.Blog.Feature.Blog
{

	
	/// <summary>
	/// BlogPost
	/// <para></para>
	/// <para>Path: /sitecore/templates/Feature/Blog/Blog Post</para>	
	/// <para>ID: bd48d35d-ae82-4269-8e9e-b21a5f17b363</para>	
	/// </summary>
	public partial class BlogPost 
	{
			public const string TemplateIdString = "bd48d35d-ae82-4269-8e9e-b21a5f17b363";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Blog Post";

			   
			public const string BodyFieldIdRaw = "1aa7b20f-f9cb-4d62-8ea1-10e688c8cd85";
			public static readonly ID BodyFieldId = new ID("1aa7b20f-f9cb-4d62-8ea1-10e688c8cd85");
			public const string BodyFieldName = "Body";
			
			   
			public const string PublishDateFieldIdRaw = "24604281-35a6-4600-8890-081e79f1b0ab";
			public static readonly ID PublishDateFieldId = new ID("24604281-35a6-4600-8890-081e79f1b0ab");
			public const string PublishDateFieldName = "Publish Date";
			
			   
			public const string SummaryFieldIdRaw = "0eddfefb-fcc9-4b53-843b-b0acb10adc21";
			public static readonly ID SummaryFieldId = new ID("0eddfefb-fcc9-4b53-843b-b0acb10adc21");
			public const string SummaryFieldName = "Summary";
			
			   
			public const string TitleFieldIdRaw = "9e2f62d5-f204-4a4d-be1c-c6fb194e1226";
			public static readonly ID TitleFieldId = new ID("9e2f62d5-f204-4a4d-be1c-c6fb194e1226");
			public const string TitleFieldName = "Title";
			
			   
			public const string AuthorsFieldIdRaw = "990d2a0c-1c4f-4db9-9cd2-bd110bcbb4f1";
			public static readonly ID AuthorsFieldId = new ID("990d2a0c-1c4f-4db9-9cd2-bd110bcbb4f1");
			public const string AuthorsFieldName = "Authors";
			
			   
			public const string CategoriesFieldIdRaw = "9eea7505-a172-4772-9164-61818f59e299";
			public static readonly ID CategoriesFieldId = new ID("9eea7505-a172-4772-9164-61818f59e299");
			public const string CategoriesFieldName = "Categories";
			
			   
			public const string TagsFieldIdRaw = "7a15403a-1086-4334-9610-bcee8db49cd9";
			public static readonly ID TagsFieldId = new ID("7a15403a-1086-4334-9610-bcee8db49cd9");
			public const string TagsFieldName = "Tags";
			
			}
}
﻿








namespace Sitecore.Feature.Blog.Sitecore.Feature.Blog.Feature.Blog
{

	
	/// <summary>
	/// BlogCategories
	/// <para></para>
	/// <para>Path: /sitecore/templates/Feature/Blog/Blog Categories</para>	
	/// <para>ID: c8ce3a4e-101c-471a-9c9b-3b079a0cc365</para>	
	/// </summary>
	public partial class BlogCategories 
	{
			public const string TemplateIdString = "c8ce3a4e-101c-471a-9c9b-3b079a0cc365";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Blog Categories";

			}
}
﻿








namespace Sitecore.Feature.Blog.Sitecore.Feature.Blog.Feature.Blog
{

	
	/// <summary>
	/// Blog
	/// <para></para>
	/// <para>Path: /sitecore/templates/Feature/Blog/Blog</para>	
	/// <para>ID: e58b747b-d2d4-4db9-a535-0dec41bc4f2a</para>	
	/// </summary>
	public partial class Blog 
	{
			public const string TemplateIdString = "e58b747b-d2d4-4db9-a535-0dec41bc4f2a";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Blog";

			}
}
﻿








namespace Sitecore.Feature.Blog.Sitecore.Feature.Blog.Feature.Blog
{

	
	/// <summary>
	/// BlogTags
	/// <para></para>
	/// <para>Path: /sitecore/templates/Feature/Blog/Blog Tags</para>	
	/// <para>ID: ee583523-4cd9-4235-83c2-96c4aef68986</para>	
	/// </summary>
	public partial class BlogTags 
	{
			public const string TemplateIdString = "ee583523-4cd9-4235-83c2-96c4aef68986";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Blog Tags";

			}
}
